### ISSUE TITLE
use tre instead of agrep

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [megabaks/portconf#5]
Since agrep isn't free software, could you port portconf to use tre instead?
https://github.com/laurikari/tre/

**Comment by megabaks** [comment]
Not now: i don't have gentoo for tests.
Agrep used in only one cycle: maybe you can try to fork portconf?
/Sorry my english.

**Comment by Alessandro-Barbieri** [comment]
I'll close this because tre provides an `agrep` command
